
[functions.send-wishlist-notification]
enabled = true
verify_jwt = true
import_map = "./functions/send-wishlist-notification/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-wishlist-notification/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-wishlist-notification/*.html" ]

[functions.send-calendar-invite]
enabled = true
verify_jwt = false
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-calendar-invite/index.ts"
# Calendar invite function for sending pickup and return reminders
