import { supabase } from '../lib/supabase';
import type { CartItem, PromoItem } from '../types';

export interface OrderFormData {
  name: string;
  email: string;
  pickupDate: Date | null;
  returnDate: Date | null;
  eventStartDate: Date | null;
  eventEndDate: Date | null;
}

export interface StaleCartItem {
  item: CartItem;
  currentAvailable: number;
  requestedQuantity: number;
}

export interface ValidationResult {
  isValid: boolean;
  staleItems: StaleCartItem[];
  unavailableItems: CartItem[];
}

/**
 * Validates that all cart items are still available with requested quantities
 */
export async function validateCartAvailability(cartItems: CartItem[]): Promise<ValidationResult> {
  if (cartItems.length === 0) {
    return { isValid: true, staleItems: [], unavailableItems: [] };
  }

  const itemIds = cartItems.map(item => item.id);
  
  const { data: currentItems, error } = await supabase
    .from('promo_items')
    .select('id, available_quantity, name')
    .in('id', itemIds);

  if (error) {
    throw new Error(`Failed to validate cart: ${error.message}`);
  }

  const staleItems: StaleCartItem[] = [];
  const unavailableItems: CartItem[] = [];

  cartItems.forEach(cartItem => {
    const currentItem = currentItems?.find(item => item.id === cartItem.id);
    
    if (!currentItem) {
      // Item no longer exists
      unavailableItems.push(cartItem);
    } else if (currentItem.available_quantity === 0) {
      // Item is now out of stock
      unavailableItems.push(cartItem);
    } else if (currentItem.available_quantity < cartItem.requestedQuantity) {
      // Item has less quantity than requested
      staleItems.push({
        item: cartItem,
        currentAvailable: currentItem.available_quantity,
        requestedQuantity: cartItem.requestedQuantity
      });
    }
  });

  return {
    isValid: staleItems.length === 0 && unavailableItems.length === 0,
    staleItems,
    unavailableItems
  };
}

/**
 * Creates an order in the database
 */
export async function createOrder(formData: OrderFormData, status: 'pending' | 'wishlist_only' = 'pending'): Promise<{ orderId: string; orderNumber: string | null }> {
  const { data: orderData, error: orderError } = await supabase
    .from('orders')
    .insert([{
      user_name: formData.name,
      user_email: formData.email,
      checkout_date: formData.pickupDate?.toISOString().split('T')[0],
      return_date: formData.returnDate?.toISOString().split('T')[0],
      status
    }])
    .select('id')
    .single();

  if (orderError) {
    throw new Error(`Order creation failed: ${orderError.message}`);
  }

  const orderId = orderData.id;

  // Refetch to get the order_number (generated by trigger)
  const { data: refetchedOrder } = await supabase
    .from('orders')
    .select('order_number')
    .eq('id', orderId)
    .single();

  return {
    orderId,
    orderNumber: refetchedOrder?.order_number || null
  };
}

/**
 * Creates checkout records and updates inventory
 */
export async function createCheckoutRecords(orderId: string, cartItems: CartItem[]): Promise<void> {
  for (const item of cartItems) {
    // Create checkout record
    const { error: checkoutError } = await supabase
      .from('checkouts')
      .insert([{
        order_id: orderId,
        item_id: item.id,
        quantity: item.requestedQuantity
      }]);

    if (checkoutError) {
      console.error(`Failed to create checkout for item ${item.id}:`, checkoutError);
      continue;
    }

    // Update inventory
    const { data: itemData } = await supabase
      .from('promo_items')
      .select('available_quantity')
      .eq('id', item.id)
      .single();

    if (itemData) {
      const newQuantity = Math.max(0, (itemData.available_quantity || 0) - item.requestedQuantity);
      
      await supabase
        .from('promo_items')
        .update({ available_quantity: newQuantity })
        .eq('id', item.id);
    }
  }
}

/**
 * Saves wishlist items to the database
 */
export async function saveWishlistItems(
  orderId: string,
  wishlistItems: CartItem[],
  formData: OrderFormData
): Promise<void> {
  const wishlistRequestsPayload = wishlistItems.map(item => ({
    user_name: formData.name,
    user_email: formData.email,
    order_id: orderId,
    item_id: item.id,
    requested_quantity: item.requestedQuantity,
    requested_pickup_date: formData.pickupDate!.toISOString().split('T')[0],
    requested_return_date: formData.returnDate!.toISOString().split('T')[0],
    event_start_date: formData.eventStartDate!.toISOString().split('T')[0],
    event_end_date: formData.eventEndDate!.toISOString().split('T')[0],
    status: 'pending'
  }));

  const { error: wishlistError } = await supabase.rpc(
    'add_wishlist_requests',
    { requests: wishlistRequestsPayload }
  );

  if (wishlistError) {
    throw new Error(`Failed to save wishlist request: ${wishlistError.message}`);
  }
}

/**
 * Sends notifications for the order
 */
export async function sendOrderNotifications(
  orderId: string,
  orderNumber: string | null,
  formData: OrderFormData,
  cartItems: CartItem[],
  wishlistItems: CartItem[]
): Promise<void> {
  const notificationPayload = {
    orderId: orderNumber || orderId || 'N/A',
    customerName: formData.name,
    customerEmail: formData.email,
    pickupDate: formData.pickupDate?.toLocaleDateString(),
    returnDate: formData.returnDate?.toLocaleDateString(),
    eventStartDate: formData.eventStartDate?.toLocaleDateString(),
    eventEndDate: formData.eventEndDate?.toLocaleDateString(),
    checkedOutItems: cartItems.map(item => ({ name: item.name, quantity: item.requestedQuantity })),
    wishlistItems: wishlistItems.map(item => ({ name: item.name, quantity: item.requestedQuantity }))
  };

  // Send notifications - don't throw on failure
  try {
    await supabase.functions.invoke('send-order-notification', { body: notificationPayload });
  } catch (e) {
    console.error('Failed to send admin notification:', e);
  }

  try {
    await supabase.functions.invoke('send-user-confirmation', { body: notificationPayload });
  } catch (e) {
    console.error('Failed to send user confirmation:', e);
  }
}

/**
 * Sends Power Automate webhook
 */
export async function sendPowerAutomateWebhook(
  orderId: string,
  orderNumber: string | null,
  formData: OrderFormData
): Promise<void> {
  const powerAutomatePayload = {
    orderId: orderNumber || orderId,
    customerName: formData.name,
    customerEmail: formData.email,
    pickupDate: formData.pickupDate?.toISOString().split('T')[0],
    returnDate: formData.returnDate?.toISOString().split('T')[0],
    eventStartDate: formData.eventStartDate?.toISOString().split('T')[0],
    eventEndDate: formData.eventEndDate?.toISOString().split('T')[0]
  };

  try {
    await supabase.functions.invoke('send-power-automate-webhook', { body: powerAutomatePayload });
  } catch (e) {
    console.error('Power Automate webhook failed:', e);
  }
}
